### ISSUE TITLE
Feature request: please add bluetooth module to firmware 

### ISSUE THREAD

**Issue by sylvain-lp** [russhughes/st7789s3_esp_lcd#1]
Hello and congratulations on this brilliant st7789 library upgrade for ESP32 S3 LCD. Very well documented.

I have successfully run many tests from your examples folder on my [Lilygo T-Display ES32  S3](https://www.lilygo.cc/products/t-display-s3?variant=42284559827125) using image:
`MicroPython v1.19.1-543-gab317a0d6-dirty on 2022-10-30; ESP32S3 module (spiram) with ESP32S3`

I would need to display & connect to Bluetooth BLE devices with the T-Display S3, but could not find any core "bluetooth" or "ubluetooth" or "ble" modules on the board when running `help('modules')`.
I have tried importing modules using `mip.install("aioble")`  but 'bluetooth' module is also a prerequisite.
If there is enough memory left, could you please consider adding "bluetooth" module to your version of driver.
(My project is to display MIDI events coming from digital piano over Bluetooth BLE).
Any pointer to what I could be missing, or way to achieve "bluetooth" connectivity with this driver is warmly welcome.

Sylvain

**Comment by russhughes** [comment]
Updated firmware with bluetooth.

**Comment by sylvain-lp** [comment]
> Updated firmware with bluetooth.

oh, this is wunderful. I'm really spoiled. thanks. I am downloading and testing to see if I can display BLE devices around.
this might be the **only** firmware available today for LILYGO T-Display S3 with accelerated Display and Bluetooth capabilities in micropython. 
Great job and thanks for sharing all these efforts.

Sylvain
