### ISSUE TITLE
target_ include_ Directories, should it be corrected?

### ISSUE THREAD

**Issue by Wind-stormger** [russhughes/st7789s3_esp_lcd#2]
https://github.com/russhughes/st7789s3_esp_lcd/blob/38f7dedb3fd814e239983684d24f20ee0f49dbe5/st7789/micropython.cmake#L16
```sh
CMake Error at /home/esp-dev/esp-idf/tools/cmake/component.cmake:301 (message):
  Include directory
  '/Volumes/MicroPython/esp-idf-4.4.2/components/esp_lcd/include' is not a
  directory.
```

should it be corrected?

**Comment by russhughes** [comment]
I had issues compiling for the S3 with 4.4.2, so I used 4.4.3.

**Comment by Wind-stormger** [comment]
Thank you. 
The version of idf4.4.3 is available.

**Comment by Wind-stormger** [comment]
https://github.com/russhughes/st7789s3_esp_lcd/blob/38f7dedb3fd814e239983684d24f20ee0f49dbe5/st7789/micropython.cmake#L16

I think this is also the point that should be prompted in README. 

It may be the path that needs to be modified to be actually used.

**Comment by russhughes** [comment]
You are correct, that should not be hardcoded.
