### ISSUE TITLE
TypeError: 'width' argument required

### ISSUE THREAD

**Issue by mcctuxic** [russhughes/st7789s3_esp_lcd#3]
(I am on GENTOO Linux)
After flashing the firmware.bin file to my TTGO Display S3 I tried scroll.py and hello.py via Thonny. The dependancies
were stored on the board beforehand.
Starting scroll.py or hello.py both results in this error message:

>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "tft_config.py", line 15, in config
TypeError: 'width' argument required
>>> 
How can I avoid this ?

**Comment by russhughes** [comment]
Make sure you are using the latest firmware.bin and tft_config.py files.

The tft_config.py file should like this:

```
""" LilyGo T-DISPLAY-S3 170x320 ST7789 display """

from machine import freq
import st7789

TFA = 0
BFA = 0

freq(240_000_000)

def config(rotation=0, options=0):
    return st7789.ST7789(
        170,
        320,
        48, 47, 46, 45, 42, 41, 40, 39,
        wr=8,
        rd=9,
        reset=5,
        dc=7,
        cs=6,
        backlight=38,
        power=15,
        rotation=rotation,
        options=options)
```

**Comment by mcctuxic** [comment]
Thank you for the super fast reply! I fixed it just a minute before myself: The flash process was somehow corrupted. I reflashed the firmware and it works flawlessly. Great stuff it is :) Cheers!
