### ISSUE TITLE
Recreation of the build process of the firmware (micropython): Pull failed

### ISSUE THREAD

**Issue by mcctuxic** [russhughes/st7789s3_esp_lcd#4]
(sorry, no native speaker here...)

I am trying to recreate the micropython firmware as an exercise for myself.

These steps work:
_git clone -b v4.4.3 --recursive https://github.com/espressif/esp-idf.git
cd esp-idf/_

But this one:
_git pull_

gives me this error:
_You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

[1]    2237 exit 1     git pull_

At which branch the git repo is supposed to be - what did I wrong?
(I am using git 2.40.0 on a GENTOO Linux system.)

**Comment by russhughes** [comment]
That should be `git checkout v4.4.3`
