### ISSUE TITLE
Precompiled firmware.bin fails to boot on new T-Display-S3

### ISSUE THREAD

**Issue by tombelpasso** [russhughes/st7789s3_esp_lcd#5]
I was very excited to get this board but am still trying to get the display working in Micropython.  I have installed the binary from the Micropython download site:
GENERIC_S3-20230426-v1.20.0.bin but it doesn't have the lcd module with it.

INSTALLATION
----------------
I downloaded the firmware/T-Display-S3/firmaware.bin from git and installed using:
 python -m esptool --chip esp32s3 --port com4 write_flash -z 0x1000 .\firmware.bin
esptool.py v4.6.2
Serial port com4
Connecting...
Failed to get PID of a device on com4, using standard reset sequence.

Chip is ESP32-S3 (revision v0.2)
Features: WiFi, BLE
Crystal is 40MHz
MAC: ec:da:3b:62:e9:ec
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00001000 to 0x0019efff...
Compressed 1695600 bytes to 1056256...
Wrote 1695600 bytes (1056256 compressed) at 0x00001000 in 15.0 seconds (effective 902.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

BOOT MESSAGES
-------------------
After hitting the reset button I get repeating reboots with the following messages:
SP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0x2a (SPI_FAST_FLASH_BOOT)
Saved PC:0x40043ac8
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0xf34
load:0x403c9700,len:0xc3c
load:0x7972746e,len:0x6f6e202c
Invalid image block, can't boot.
ets_main.c 329

SUMMARY
------------
I also tried using -z 0 for the esptool but it didn't work either.  I have the Expressif download tool, but haven't gotten it  to work for the Micropython flash files.

Thanks for producing this display code.  I hope it simply my user error.

**Comment by tombelpasso** [comment]
UPDATE:
I tried installing again, using -z 0x0000 and I get the following repeating message on booting:

The filesystem appears to be corrupted. If you had important data there, you
may want to make a flash snapshot to try to recover it. Otherwise, perform
factory reprogramming of MicroPython firmware (completely erase flash, followed
by firmware programming).

SOLUTION:
The solution is to erase the flash just like you suggested in your documentation, then set the starting address to 0x0000 instead of 0x1000.

Here are the commands that I used that worked:
` python -m esptool --chip esp32s3 --port com4 erase_flash`
`python -m esptool --chip esp32s3 --port com4 write_flash -z 0x0000 .\firmware.bin`

Change --port as needed.  

You should update the instructions for the correct chip and starting location.
Thanks again.

**Comment by russhughes** [comment]
The -z address was definitely wrong, it should be 0x0 for ESP32-S3s.
